var bodegas=[];
bodegas.push( new Bodega(1,"Bodegas Caro","bodega-caro.jpg","La Bodega se encuentra ubicada en Cruz de Piedra, Maipú, Región Central de Mendoza. Es un edificio del año 1970 construido por el arquitecto Francisco “Chicho” Pitela , con estilo mediterráneo de amplias galerías, arcadas y vitreaux que otorgan una iluminación muy cálida y dotan de un entorno propio del arte con que se elaboran los vinos. La bodega se encuentra rodeada de viñedos y olivos propios, con vista hacia la cordillera, destacando el cerro Tupungato y el conocido Cordón del Plata. Bodega Argento mantiene un espíritu constante de mejora, uniendo la tecnología con la pasión, el arte, el saber y la tradición enológica argentina, con una clara visión en la sustentabilidad y el medio ambiente."));
bodegas.push( new Bodega(2,"Bodega Poesia","bodega-poesia.jpg","La Bodega Poesía es el resultado de la unión entre el savoir faire de Hélène Garcin-Lévêque y Patrice Lévêque, un matrimonio de viticultores franceses con generaciones en el oficio, que dirigen la enología en varios chateaux world class bordeleses y un viñedo de características muy especiales en la zona antigua de Luján de Cuyo, Mendoza. El objetivo de dicha fusión es lograr los mejores vinos que pueden provenir de ese gran terroir argentino; vinos dirigidos al consumidor internacional contemporáneo, que sin embargo conservan la elegancia y el estilo tan característicos que distinguen a los grandes vinos de los buenos vinos."));
bodegas.push( new Bodega(3,"Bodega Catena Zapata","bodega-catena-zapata.jpg","Este vino proviene de una pequeña parcela en un viñedo de más de 80 años de antigüedad cuyos rendimientos en kilos de uva por planta son sumamente bajos, lográndose por ello una concentración y complejidad excepcionales. Esta Parcela fue plantada por el mismo Nicola Catena, primera generación de la familia y bisabuelo de Laura Catena, a principios de 1900. Los parrales de este viñedo tan antiguo, hoy en día dan vida a una de las bonardas más complejas y atractivas de nuestro país."));
bodegas.push( new Bodega(4,"Zuccardi","bodega-zuccardi.jpg","Familia Zuccardi es una empresa familiar fundada en 1963 por el Ing. Alberto Zuccardi. Hoy, desde sus viñedos ubicados en Valle de Uco, Maipú y Santa Rosa, provincia de Mendoza, es reconocida como una bodega hacedora de grandes vinos y con un claro compromiso con la calidad, la innovación y la producción sustentable. A partir del año 2003, los nietos de los fundadores comenzaron a tener una participación activa en el desarrollo de la empresa familiar mediante el aporte de nuevos proyectos. Sebastián, el mayor de los tres hijos de José Alberto se encuentra al frente del desarrollo de las fincas que la bodega posee en la región del Valle de Uco. En esa región, Sebastián lidera un intenso trabajo de detección de los mejores terroirs y micro terroirs con el fin de obtener vinos únicos, que expresen cabalmente a sus lugares de origen."));
bodegas.push( new Bodega(5,"Viña Cobos","vina-cobos.jpg","Viña Cobos elabora vinos que expresan naturalmente el terruño del que provienen. Paul Hobbs, socio fundador y enólogo de Viña Cobos, trabaja desde 1997 en la exploración de los distintos terroirs de Mendoza, buscando las regiones más destacadas dentro de Luján de Cuyo y Valle de Uco, para la elaboración de vinos únicos. Un manejo sustentable del viñedo permite lograr cosechas equilibradas y fruta de gran calidad, a partir de allí un trato cuidadoso de la uva y un meticuloso proceso de elaboración, da lugar a vinos complejos y elegantes, de gran sutileza y balance."));
bodegas.push( new Bodega(6,"Champagne Barons de Rothschild","champagne-rothschild.jpg","El nombre de Rothschild simboliza la excelencia en el mundo del vino a nivel global. Champagne Barons de Rothschild nace de la inquietud por parte de las tres ramas de la familia por unir conocimiento e innovación. El resultado es la creación del ilustre Champagne Barons de Rothschild revalorizando la categoría del Champagne de la mano de un producto de excepcional calidad."));
bodegas.push( new Bodega(7,"Bodega Luca", "bodega-luca.jpg", "Laura Catena tiene una visión de creación de una nueva generación de vinos argentinos: pequeñas cantidades, calidad artesanal, y fiel a los terruños individuales. Ella comienza con algunas de las mejores frutas de la Argentina de bajo rendimiento y viñedos de altura. Basado en el arte de la vinificación y su crianza en roble (principalmente francés) elevó los vinos a un nivel de calidad exigido por los verdaderos conocedores del vino. Ellos son la máxima expresión de la rigurosa gestión de los viñedos, la experimentación vitícola, estrictos controles de riego, elaboración de vinos calificados, y una búsqueda de la calidad incesante."));
bodegas.push( new Bodega(8,"La Posta Vineyards", "laposta.jpg", "La Posta es la línea joven de vinos de Bodega LUCA. Cada etiqueta rinde homenaje a un productor de vinos que entrega la uva para su elaboracion. Este proyecto es el sueño de Laura Catena con el cual reconoce a familias viticultoras, pequeños viñedos familiares seleccionados por ella misma por su excepcional calidad de uva. Las familias que integran La Posta son descendientes de italianos. Es sólo cuestión de probar una copa de estos vinos para que se queden en tu familia para siempre."));
bodegas.push( new Bodega(9,"Terrazas de los Andes", "terrazas-delosandes.jpg", "Aquí en Terrazas de los Andes, somos argentinos, somos franceses, todos nos dedicamos al vino y trabajamos codo a codo todos los días. Cada uno de nosotros trajo saberes distintos y complementarios de diversas experiencias alrededor del mundo, pero una pasión en común por aprender e innovar en la búsqueda de un mejor vino. Esta es la Argentina: una mezcla continua de culturas inspirada en los mismos valores que impulsaron a nuestros fundadores, y que contribuye a dar forma a una identidad única y viva."));
bodegas.push( new Bodega(10,"Chandon", "chandon.jpg", "Para muchos, 60 años es toda una vida. Para nosotros, es apenas el comienzo. Estamos orgullosos del camino que recorrimos hasta aquí. Un camino de actos pioneros y hazañas que han marcado nuestra esencia desde nuestra fundación a los pies de La Cordillera de los Andes en 1959. Las burbujas son el corazón de nuestra compañía y son aquello a lo que nos dedicamos desde nuestros orígenes. Son años de aprendizajes y saberes, de esfuerzos y celebraciones, desplegados con sabiduría y pasión para elaborar Chandon. Somos especialistas en burbujas, nacimos para elaborarlas, esa es nuestra razón de ser."));
bodegas.push( new Bodega(11,"Domaine Nico", "domaine-nico.jpg", "Domaine Nico es el nuevo proyecto personal de Laura Catena. Podría decirse que comenzó a gestarse cuando los primeros clones de Pinot Noir Dijon fueron plantados por Nicolás Catena en Villa Bastías, Mendoza. Ya en 1999, esas uvas fueron elaboradas para el proyecto LUCA y en 2003 se dio inicio al trabajo de evaluar las parcelas, clones, diferentes sistemas de vinificación y el uso preciso del roble. Finalmente, en 2016 se decidio embotellar las primeras botellas de parcelas que produjeron los vinos más característicos de Pinot Noir, reflejando el terruño y el clima de cada parcela."));
bodegas.push( new Bodega(12,"Antinori", "antinori.jpg", "Originaria de Florencia, la familia Antinori elabora vinos desde hace 26 generaciones. Su legado histórico data de 1385, cuando Giovanni di Piero Antinori se convirtió en miembro del Arte Fiorentina dei Vinattieri, el gremio de productores de vino de la ciudad. Aunque esta impresionante cantina se encuentra en el corazón de la Toscana, son ocho las bodegas Antinori que se reparten en las regiones italianas de Toscana y Umbría: Fattoria Aldobrandesca, Le  Mortele, La Braccesca, Tenuta Monteloro, Prunotto, Montenisa, Tormaresca y Santa Cristina."));
bodegas.push( new Bodega(13,"Bodega Weinert", "bodega-weinert.jpg", "Ubicada en la provincia argentina de Mendoza, Bodega & Cavas de WEINERT fue construida en 1890 por el inmigrante español Ramón Otero y fundada en 1975 por el brasilero de origen alemán Don Bernardo Weinert. La misión de quien porta el arte del vino* en su apellido y da nombre a su empresa familiar se sostiene desde hace más de cuarenta años: producir vinos de alta calidad. El conjunto arquitectónico de Bodega & Cavas de WEINERT remite al paisaje de las villas italianas. Entre sus piezas únicas se destaca el tonel en uso más grande del país, construido en roble francés, con capacidad de 44.000 litros. Desde 1996 la producción se encuentra a cargo del enólogo suizo Hubert Weber quien, con tan solo 27 años, llegó a Luján de Cuyo para quedarse."));
bodegas.push( new Bodega(14,"Bodega La Libertad", "bodega-lalibertad.jpg", "Pasarisa y Altaland, son las dos líneas que integran bodega La Libertad. A través de sus etiquetas viajamos por las principales regiones vitinícolas de la Argentina (Salta, La Rioja, Mendoza y Patagonia) en búsqueda de las cepas más características de cada lugar. Son vinos jóvenes y listos para disfrutar en cualquier momento."));
bodegas.push( new Bodega(15,"Escorihuela Gascón", "escorihuela-gascon.jpg", "En 1884 Don Miguel Escorihuela Gascón, hombre muy visionario y de gran tesón, dio origen en Mendoza a una de las empresas vitivinícolas de mayor prestigio de la República Argentina: Establecimientos Vitivinícolas Escorihuela. Desde la primera hora, su objetivo fue lograr vinos de máxima calidad. Por ello, siempre se tuvo muy en cuenta la elección y cuidado de los cepajes, la elaboración bajo métodos artesanales y la permanente incorporación de tecnología, con un equipo de calificados profesionales argentinos y el asesoramiento de reconocidos enólogos y técnicos extranjeros, que permiten mantener un alto nivel de calidad internacional. Hoy, con más de 130 años innovando en vinos de máxima calidad, Escorihuela Gascón es líder en la elaboración de vinos Premium y de Alta Gama y una de las 10 bodegas exportadoras más importantes."));
bodegas.push( new Bodega(16,"Bodega Rolland", "bodega-rolland.jpg", "La bodega propiedad del enólogo más famoso del mundo, el francés Michel Rolland, junto a su esposa Dany, es la última construcción del Clos de los Siete, y se encuentra precisamente en el último confín de la propiedad de 850 hectáreas, prácticamente donde la Cordillera de los Andes “aterriza” en su entrada. La bodega, de 3.200 metros cuadrados, tiene un estilo simple y racionalista, es un verdadero “galpón” para hacer vinos de calidad, tiene 54 piletas de 10 mil litros cada una, y está diseñada para evitar el uso de bombas con un sistema gravitacional."));
bodegas.push( new Bodega(17,"Abras", "abras.jpg", "Karim Mussi está en la permanente búsqueda de la expresión única de cada terruño. Abras es apenas el primer capítulo de una larga historia que comenzó cuando se enamoró de Cafayate, un desierto de altura ubicado en Salta a 1750 m.s.n.m (cuna del Torrontés y de grandes Malbecs). Las uvas se seleccionan de vides con más de 30 años de edad, plantadas sobre suelos aluvionales al pie del valle, obteniendo así, expresiones más minerales y genuinas. Del mismo modo en que los Incas utilizaban los Abras como caminos para transitar las montañas, nosotros aprovechamos éste portal místico para acceder al maravilloso mundo del vino del Valle Calchaquí."));
bodegas.push( new Bodega(18,"Mosquita Muerta Wines", "mosquita-muerta.jpg", "El mismo está focalizado en la elaboración de Blends Premium. Para ello se realiza una cuidadosa selección de diferentes variedades ubicadas en Viñedos propios y de terceros en las zonas más importantes de Mendoza. Malbec, Cabernet Sauvignon, Cabernet Franc, Syrah, Bonarda y Merlot son algunas de las variedades tintas que se utilizan para darle vida a los 4 Vinos tintos que componen este proyecto. A partir de 2014 se comenzó a trabajar con uvas blancas como Chardonnay, Viognier, Sauvignon Blanc y Moscatel de Alejandría para la elaboración de una serie de Vinos blancos que fueron lanzados al mercado a fines de 2015. Viñedos ubicados en Gualtallary, Vista Flores, Chacayes, Tupungato, La Consulta, Los Arboles, Altamira, Perdriel y Medrano son los que le dan vida a este emprendimiento."));
bodegas.push( new Bodega(19,"Bodega Toneles", "bodega-toneles.jpg", "La nueva línea de vinos de la familia Millán está compuesta por cuatro segmentos bien diferenciados. El nombre proviene de un juego de palabras: asado, abrazo, amigos y brasa. Todos vinos elaborados con uvas de Mendoza, donde el “entry level” es el Blend de Parcelas. Luego hay un segundo segmento, Terroir Selection; el tercer nivel denominado Historic Blend y dos tope de gama, los Unique Parcel, con un Malbec y un Cabernet Franc. “Son vinos pensados para la gastronomía y para maridar fácilmente con un asado”, destaca el enólogo Bernardo Bossi, quien tiene a cargo la enología de la bodega junto a su coequiper Cristian Ampuero."));
bodegas.push( new Bodega(20,"Fuego Blanco", "fuego-blanco.jpg", "Fuego blanco es el más reciente emprendimiento vitivinícola de la familia Millán. Inicia en 2012 con la adquisición de una finca en la zona más alta y exclusiva del valle de pedernal. El valle de pedernal se ubica en la provincia de San juan, en el límite con mendoza, recostado en el pedemonte de la cordillera de los andes a una altura que va desde los 1.200 a los 1.700 msnm, con veranos templados y noches muy frescas. Fuego blanco representa la búsqueda para lograr los mejores vinos obtenidos en estos suelos. Vivaces vinos single-vineyard provenientes de Valle de Pedernal, San Juan. Exploramos la exuberancia de un suelo."));
bodegas.push( new Bodega(21,"Bodega Vistalba", "bodega-vistalba.jpg", "Bodega Vistalba fue fundada en Mendoza en el año 2003 por Carlos Pulenta, tercera generación de una tradicional familia bodeguera. Construyó la bodega en una finca familiar en Vistalba Luján de Cuyo Mendoza y comenzó así a volcar toda su experiencia y pasión por hacer vinos en un proyecto familiar. La larga historia de la familia Pulenta, sus históricos viñedos junto a modernas técnicas vitícolas, se aunaron en el objetivo de elaborar vinos elegantes, a la altura de los grandes vinos del mundo. En el año 2009 se incorporó como socio el Ingeniero Alejandro Bulgheroni."));
bodegas.push( new Bodega(22,"Bodega Alandes", "bodega-alandes.jpg", "Alandes, (combinación de palabras que indica Vinos producidos a lo largo de Los Andes) es uno de los proyectos de Karim Mussi, que junto a sus socios encontró una hermosa bodega centenaria para desarrollar nuevas marcas y estilos sin la restricción de producir vinos con uvas provenientes de un terruño específico. Cada etiqueta de Alandes es motivada por un concepto singular, el cual representa libertad absoluta, una filosofía enológica Laissez Faire que se esparce en un territorio extenso, sin límites."));
bodegas.push( new Bodega(23,"Bodega Argento", "artesano.jpg", "La Bodega se encuentra ubicada en Cruz de Piedra, Maipú, Región Central de Mendoza. Es un edificio del año 1970 construido por el arquitecto Francisco “Chicho” Pitela , con estilo mediterráneo de amplias galerías, arcadas y vitreaux que otorgan una iluminación muy cálida y dotan de un entorno propio del arte con que se elaboran los vinos. La bodega se encuentra rodeada de viñedos y olivos propios, con vista hacia la cordillera, destacando el cerro Tupungato y el conocido Cordón del Plata. Bodega Argento mantiene un espíritu constante de mejora, uniendo la tecnología con la pasión, el arte, el saber y la tradición enológica argentina, con una clara visión en la sustentabilidad y el medio ambiente."));
bodegas.push( new Bodega(24,"Bodega Monteviejo", "bodega-monteviejo.jpg", "Bodega Monteviejo está situada al pie de la Cordillera de los Andes, en el corazón de Valle de Uco, una de las principales zonas vitivinícolas de la Argentina: a 120 km de la ciudad de Mendoza, Vista Flores, Tunuyán, dentro del grupo de propiedades de Clos de los Siete. El predio comprende 130 ha a una altitud entre los 1000 y 1200 msnm. Sus tierras con pendientes orientadas hacia el Norte y el Este tienen la mejor exposición al sol dentro del hemisferio Sur."));
bodegas.push( new Bodega(25,"Bodega Diamantes", "bodega-diamantes.jpg", "En 2005, la familia Bonnie, propietaria del reconocido Château Malartic-Lagravière (Grand Cru Classé de Graves) y del Château Gazin Rocquencourt (Pessac- Léognan) decidió partir de Francia para descubrir nuevos horizontes vitivinícolas. Todo empezó con la adquisición, junto a sus socios, de un bloque de 130 hectáreas, situado en pleno Valle de Uco, al sur de Mendoza. Allí nació la bodega DiamAndes, coproductora además del prestigioso Clos de los Siete. Sus instalaciones, cuya arquitectura se funde con los maravillosos paisajes andinos, permiten la elaboración de vinos en condiciones excepcionales desde la cosecha 2007."));
bodegas.push( new Bodega(26,"Bodega Altocedro", "bodega-altocedro.jpg", "Altocedro es una bodega enfocada en el singular terruño de La Consulta, espacio único del Valle de Uco, reconocido por la altísima calidad de sus uvas provenientes de viñedos antiguos. Desde 1999, elaboramos vino que habla distintivamente del lugar donde se origina, basándonos en el balance, elegancia y capacidad de añejamiento. Karim Mussi fue pionero de la puesta en valor de La Consulta a través de los vinos nacidos y criados allí."));

var seccionBodega = document.getElementById("bodegas");

var vermas = document.getElementById("seccion-boton");

for(let i=0; i < bodegas.length; i++) {
    let div = document.createElement("div");
    if (i<=5) {
        div.className = "primarios";
    } else {
        div.className = "secundarios1";
        div.style.display = "none";
    }

    let divContenedor = document.createElement("div");

    let h3  = document.createElement("h3");
    h3.innerHTML = bodegas[i].nombre;

    let img = document.createElement("img");
    img.id          = bodegas[i].id;
    let nombreAux = "img/" + bodegas[i].imagen;
    img.setAttribute("src", nombreAux);

    divContenedor.appendChild(img);
    div.appendChild(divContenedor);
    div.appendChild(h3);

    seccionBodega.insertBefore(div,vermas);
}

var boton1 = document.getElementById("vermas");

boton1.addEventListener("click", function() {
    var secundarios = document.getElementsByClassName("secundarios1");
    for(let i=0; i < secundarios.length; i++) {
        if (boton1.textContent == "Ver más") {
            secundarios[i].style.display = "flex";
        } else {
            secundarios[i].style.display = "none";
        }
    } 
    if (boton1.textContent == "Ver más") {
        console.log("Ver menos");
        boton1.innerText = "Ver menos";
    } else {
        boton1.innerHTML = "Ver más";
    }
});


function Bodega(id, nombre, imagen, descripcion) {
    this.id = id;
    this.nombre = nombre;
    this.imagen = imagen;
    this.descripcion = descripcion;
}